name: Build and Push to ACR

on:
  push:
    branches:
      - main  # 在 main 分支推送代码时触发

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout Code
        uses: actions/checkout@v3

      # 登录到阿里云 ACR
      - name: Log in to ACR
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login --username "${{ secrets.ACR_USERNAME }}" --password-stdin "${{ secrets.ACR_REGISTRY }}"

      # 构建 Docker 镜像
      - name: Build Docker Image
        run: |
          docker build -t "${{ secrets.ACR_REGISTRY }}/${{ secrets.ACR_REPOSITORY }}:latest" .

      # 推送 Docker 镜像到 ACR
      - name: Push Docker Image to ACR
        run: |
          docker push "${{ secrets.ACR_REGISTRY }}/${{ secrets.ACR_REPOSITORY }}:latest"
